### ISSUE TITLE
capi Makefile.am missing OpenCV CFLAGS

### ISSUE THREAD

**Issue by ngaloppo** [intel/libxcam#508]
Needs a `#(OPENCV_CFLAGS)` line here: https://github.com/01org/libxcam/blob/master/capi/Makefile.am#L9

**Comment by windyuan** [comment]
thanks for pointing this out. @liuyinhangx please fix.

**Comment by liuyinhangx** [comment]
@ngaloppo 
Could you please provide the error log?
I can't reproduce this issue on my platform(Ubuntu 16.04), it seems that capi module does not use opencv, thanks.

**Comment by ngaloppo** [comment]
See below. Looks like `cl_image_360_stitch.h` uses OpenCV. 

```
In file included from ../modules/ocl/cv_base_class.h:32:0,
                 from ../modules/ocl/cv_feature_match.h:31,
                 from ../modules/ocl/cl_image_360_stitch.h:30,
                 from context_priv.cpp:32:
../modules/ocl/cv_context.h:38:30: fatal error: opencv2/opencv.hpp: No such file or directory
compilation terminated.
Makefile:516: recipe for target 'libxcam_capi_la-context_priv.lo' failed
```
