### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by mualloc** [intel/libxcam#515]
Hello,
I could not locate any tutorial in neither libXCam installation folder nor anywhere on the web. Is there such a facility or is libXCam is mostly about OpenCL so there is not any such specific tutorial?

**Comment by windyuan** [comment]
please see
https://github.com/01org/libxcam/wiki/
Build
https://github.com/01org/libxcam/wiki/Build
Tests
https://github.com/01org/libxcam/wiki/Tests
