### ISSUE TITLE
Media SDK for Windows - DirectX9 surfaces

### ISSUE THREAD

**Issue by richT1977** [intel/libxcam#578]
Hello,
We're looking into methods for accelerated fish eye de-warping to panorama of IP camera feeds, encoded as H264. Our platform is Windows. We use the Intel Media SDK for accelerated decode of h264 to NV12 surfaces. These surfaces are DirectX9. Have you any pointers on how to integrate LibXCam into the Media SDK environment on a Windows platform?

We see an OpenCL plugin loader and DirectX surface sharing example as part of the 2018 Media SDK (sample_plugin_opencl).
Do we therefore need a libxcam.cl file?

Thank you in advance.

**Comment by windyuan** [comment]
@richT1977,  I'm sorry, libxcam doesn't support windows as yet. 
but welcome if anyone have interests porting to windows.
