### ISSUE TITLE
does these bunch of opencl accelerated image algorithm support rgb color space ?

### ISSUE THREAD

**Issue by fulean** [intel/libxcam#591]
hi,I want to port the opencl accelerated 3dnr to mobile device, for the performance consideration, I create cl_mem from a opengles texture, in this case the texture internal format only suppoer RGBA on my device (texture with rgba format is must for opencl interop with opengl on my device),so are there any way that can applying the opencl implemented algorithm on rgba color space image?  thanks.

**Comment by zongwave** [comment]
the algorithms' opencl kernel we implemented in libxcam only support NV12 format, you have to convert color space before running the CL kernel.
