### ISSUE TITLE
Surround view layout

### ISSUE THREAD

**Issue by Tamme** [intel/libxcam#640]
When using test-surround-view, I understand that input0 - front, input1 - right,  input2 - rear,  input3 -left, but the output file has them in the same order, i.e. that front view is split between two sides of the image, and the rear image is the most center one. Is that how its planned or i have used the file incorrectly, somehow

Thank you!

**Comment by zongwave** [comment]
Yes, the horizontal direction of output image from left to right is aligned with 0 degree to 360 degree.
accordingly, the center of front view is marked as 0 degree, and increasing in counter wise. the center of right view is at 90 degree, the center of rear view is at 180 degree and the center of left view is at 270 degree.
