### ISSUE TITLE
Different view point.

### ISSUE THREAD

**Issue by tkim1310** [intel/libxcam#680]
Is there any options for different view point ?
360 degree surround view provide only top-view. 
I think, because LibXcam provide the bowl mode, there will be some kind of option to change view point.
![image_2019_09_17T01_05_45_468Z](https://user-images.githubusercontent.com/2891084/65005753-f8160000-d93b-11e9-9a6d-6dce1b23124d.png)

**Comment by wangqiang624731186** [comment]
不告诉你，哈哈
