### ISSUE TITLE
Centre of video frame had been mess up

### ISSUE THREAD

**Issue by kchoonhw** [intel/libxcam#683]
I am using this libxcam library and stitching for 4 sample input video frame to simulate the autonomous of bowl view feature. however, in the center of the car the image was mess up. May i know how can i fix it? 

![image](https://user-images.githubusercontent.com/44877913/66111444-7a204d00-e5fb-11e9-97c1-a2c297a054fa.png)

**Comment by jeongseokhwan** [comment]
hi~ i also have similar problem...
how did you get intrinsic parameter and extrinsic parameter? i got intrinsic parameter from ocam calibration and extrinsic parameter from real value(i set the camera by my self and measure the x, y, z)
![result](https://user-images.githubusercontent.com/54701946/66634141-61d9af00-ec47-11e9-9024-3c8bfaaa0317.png)

thanks~

**Comment by zongwave** [comment]
@kchoonhw you posted a topview image, which is a view form the top direction. you should know the horizontal FOV of input images is limited, no ground image captured under the car at all.
the application developer usually need to rend a car to cover the black hole in the center of topview.
