### ISSUE TITLE
Calbration for 2-fisheye equirectangular stitching

### ISSUE THREAD

**Issue by envyen** [intel/libxcam#698]
Hello team

For the dual-fisheye to equirectangular stitching, what is the recommended calibration scheme/tool used? How is the calibration parameters used in the library

Kindly share the details/steps for this

**Comment by zongwave** [comment]
to remap fisheye camera image into equirectangular image we use some intrinsic and extrinsic parameters:
principal axis (points)
radius
fov
rotation

**Comment by envyen** [comment]
Hi thanks for the details
Is there any openly available tools/source to achieve this from input images ?
Any pointers to estimate the parameters would be helpful 

> principal axis (points)
> radius
> fov
> rotation

**Comment by zongwave** [comment]
Principal axis and rotation can be acquired through OpenCV fisheye calibration tool.

Fov can be acquired from camera manufacture

Radius is in pixel unit, you can estimate the value from the fisheye image.

**Comment by envyen** [comment]
Thanks Zong Wei, the information helped
