### ISSUE TITLE
TestSurroundView Gray scale issue.

### ISSUE THREAD

**Issue by kimjihoon0301** [intel/libxcam#704]
Hello. 
I tested with your libxcam opensource.
I used black & blue colored grid pattern image.

Problem:
1. output.yuv has only upside blue grid but it's not organized well.
2. topview_output.yuv has only black color.
( I guess upside has only blue color but it's cutted.)

Please check the output yuv captcured files.

**Comment by zongwave** [comment]
can you write down the command line you used?
