### ISSUE TITLE
Configuring Lens Shading Correction in Fisheye handler

### ISSUE THREAD

**Issue by envyen** [intel/libxcam#769]
I am trying to enable lens shading correction feature in the[ fisheye handler],  for dual fisheye 360 stitching (https://github.com/intel/libxcam/blob/master/modules/ocl/cl_fisheye_handler.cpp#L27)

```C++
#define XCAM_LSC_ARRAY_SIZE 64

static const float max_gray_threshold = 220.0f;
static const float min_gray_threshold = 80.0f;

static const float lsc_array[XCAM_LSC_ARRAY_SIZE] = {
    1.000000f, 1.000150f, 1.000334f, 1.000523f, 1.000761f, 1.001317f, 1.002109f, 1.003472f,
    1.004502f, 1.008459f, 1.011816f, 1.014686f, 1.016767f, 1.018425f, 1.020455f, 1.022125f,
    1.023080f, 1.025468f, 1.029810f, 1.035422f, 1.041943f, 1.047689f, 1.054206f, 1.059395f,
    1.063541f, 1.068729f, 1.074158f, 1.082766f, 1.088606f, 1.095224f, 1.102773f, 1.112865f,
    1.117108f, 1.132849f, 1.140659f, 1.147847f, 1.157544f, 1.165002f, 1.175248f, 1.181730f,
    1.196203f, 1.205452f, 1.216974f, 1.236338f, 1.251963f, 1.269212f, 1.293479f, 1.311051f,
    1.336007f, 1.357711f, 1.385124f, 1.409937f, 1.448611f, 1.473716f, 1.501837f, 1.525721f,
    1.555186f, 1.602372f, 1.632105f, 1.698443f, 1.759641f, 1.836303f, 1.939085f, 2.066358f
};

```
Enabling with default parameter seems to degrade/brighten the seam areas wrongly

How is these parameters computed and configured for shading correction for a lens.
Any details on the implementation and how to calibrate for a particular lens in use would be helpful 

Regards
Naveen

**Comment by zongwave** [comment]
Hi, you cannot apply parameters in this LSC table on your images. you should calculate & create such kind of LSC table complies with your camera lens. 

this article explain how to generate a LUT to correct vignetting for a camera
https://pduncan.com/2015/11/19/vignetting-3/
