### ISSUE TITLE
ia_imaging library 

### ISSUE THREAD

**Issue by alexV84** [intel/libxcam#787]
Hi. Please tell me where to find the ia_imaging library. The path given to you does not exist
https: //mjia@bee.sh.intel.com/git/smartcamera/ia_imaging.git

**Comment by zongwave** [comment]
Hi, this "ia_imaging" is an Intel close source 3A algorithm library for Intel IPU (integrated ISP). We did not maintain this feature for a long time.

**Comment by alexV84** [comment]
Thanks for the quick response.
Does the CL3aImageProcessor class use the algorithms from this library?
Can libxcam be compiled with --deseble -aiq and --enable-3alib options?
Sorry for my English.

**Comment by zongwave** [comment]
NO. libXCam needs aiq 3A algorithm.
