### ISSUE TITLE
test-surround-view: command not found

### ISSUE THREAD

**Issue by lekhashreehj** [intel/libxcam#825]
When I am trying run the following code I am getting this error
test-surround-view --module soft --input input.nv12 --output output.nv12 --in-w 1920 --in-h 1080 --out-w 1920 --out-h 960 --in-format nv12 --fisheye-num 2 --res-mode 1080p2cams --blend-pyr-levels 1 --dewarp-mode sphere --scopic-mode mono --scale-mode dualconst --fm-mode capi --fm-frames 120 --fm-status fmfirst --frame-mode multi --save true --save-topview false --loop 1

Please help me to debug this error

**Comment by zongwave** [comment]
can you post the error message?

**Comment by lekhashreehj** [comment]
test-surround-view: command not found
Its showing command line not found.
I am trying to build it with CPU and not using any hardware. 
I am stuck in this step.

**Comment by shreshtashetty** [comment]
Try 
`cd tests`
And then run the whole command you posted in your question starting with `./`

**Comment by lekhashreehj** [comment]
Thank you its working!!!

**Comment by zongwave** [comment]
Thanks @shreshtashetty
